export enum ProductListActionType {
  PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR",
}

export enum ProductDetailActionType {
  PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR",
}

export enum CartActionType {
  CART_ADD_ITEM = "CART_ADD_ITEM",
  CART_REMOVE_ITEM = "CART_REMOVE_ITEM",
}

export enum AuthActionType {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL = "USER_LOGIN_FAIL",
  USER_LOGOUT = "USER_LOGOUT",
}
