export enum ProductListActionType {
  PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR",
}

export enum ProductDetailActionType {
  PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR",
}
