export enum ProductListActionType {
  PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR",
}

export enum ProductDetailActionType {
  PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_ERROR = "PRODUCT_DETAIL_ERROR",
}

export enum CartActionType {
  CART_ADD_ITEM = "CART_ADD_ITEM",
  CART_REMOVE_ITEM = "CART_REMOVE_ITEM",
}

export enum AuthActionType {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL = "USER_LOGIN_FAIL",
  USER_LOGOUT = "USER_LOGOUT",
  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL = "USER_REGISTER_FAIL",
  USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST",
  USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS",
  USER_DETAIL_FAIL = "USER_DETAIL_FAIL",
  USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL = "USER_UPDATE_FAIL",
  USER_UPDATE_RESET = "USER_UPDATE_RESET",
}
